### ISSUE TITLE
[Traefik Plugin Catalog] Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [FinalCAD/TraefikRegionalPlugin#12]
The plugin was not imported into Traefik Plugin Catalog.

Cause:
```
unsupported plugin: the module name (github.com/finalcad/TraefikRegionalPlugin) doesn't contain the GitHub repository name (github.com/FinalCAD/TraefikRegionalPlugin)
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please contact [us](https://community.traefik.io/).

**Comment by ghost** [comment]
Fix by c0d037d069ec8c280dfe83008157937969045da2
